
RUSSIAN_LETTERS = 'АБВГДЕЁЖЗИЙКЛМНОПРТУФХЦЧШЩЫЭЮЯабвгдеёжзийклмнопрстуфхцчшщыьэюя'

CHOICES_LEXERS = [
    ('Awk', 'Awk'),
    ('Base Makefile', 'Base Makefile'),
    ('Bash', 'Bash'),
    ('CoffeeScript', 'CoffeeScript'),
    ('CSS', 'CSS'),
    ('CSS+Django/Jinja', 'CSS+Django/Jinja'),
    ('CSS+PHP', 'CSS+PHP'),
    ('CSS+Ruby', 'CSS+Ruby'),
    ('Django/Jinja', 'Django/Jinja'),
    ('HTML', 'HTML'),
    ('HTML+Django/Jinja', 'HTML+Django/Jinja'),
    ('HTML+PHP', 'HTML+PHP'),
    ('IPython3', 'IPython3'),
    ('Java', 'Java'),
    ('JavaScript', 'JavaScript'),
    ('JavaScript+Django/Jinja', 'JavaScript+Django/Jinja'),
    ('JavaScript+PHP', 'JavaScript+PHP'),
    ('JavaScript+Ruby', 'JavaScript+Ruby'),
    ('JSON', 'JSON'),
    ('LessCss', 'LessCss'),
    ('Makefile', 'Makefile'),
    ('MySQL', 'MySQL'),
    ('NumPy', 'NumPy'),
    ('Perl', 'Perl'),
    ('Perl6', 'Perl6'),
    ('PHP', 'PHP'),
    ('PostgreSQL console (psql)', 'PostgreSQL console (psql)'),
    ('Python', 'Python'),
    ('Python 3', 'Python 3'),
    ('reStructuredText', 'reStructuredText'),
    ('Ruby', 'Ruby'),
    ('Sass', 'Sass'),
    ('Scala', 'Scala'),
    ('SCSS', 'SCSS'),
    ('SQL', 'SQL'),
    ('XML', 'XML'),
    ('YAML', 'YAML'),
]
