
RUSSIAN_LETTERS = 'АБВГДЕЁЖЗИЙКЛМНОПРТУФХЦЧШЩЫЭЮЯабвгдеёжзийклмнопрстуфхцчшщыьэюя'

CHOICES_LEXERS = [
    ('awk', 'Awk'),
    ('base_makefile', 'Base Makefile'),
    ('bash', 'Bash'),
    ('coffescript', 'CoffeeScript'),
    ('css', 'CSS'),
    ('css_django_jinja', 'CSS+Django/Jinja'),
    ('css_php', 'CSS+PHP'),
    ('css_ruby', 'CSS+Ruby'),
    ('django_jinja', 'Django/Jinja'),
    ('html', 'HTML'),
    ('html_django_jinja', 'HTML+Django/Jinja'),
    ('html_php', 'HTML+PHP'),
    ('ipython3', 'IPython3'),
    ('java', 'Java'),
    ('javascript', 'JavaScript'),
    ('javascript_django_jinja', 'JavaScript+Django/Jinja'),
    ('javascript_php', 'JavaScript+PHP'),
    ('javascript_ruby', 'JavaScript+Ruby'),
    ('json', 'JSON'),
    ('lesscss', 'LessCss'),
    ('makefile', 'Makefile'),
    ('mysql', 'MySQL'),
    ('numpy', 'NumPy'),
    ('perl', 'Perl'),
    ('perl6', 'Perl6'),
    ('php', 'PHP'),
    ('postgresql_console', 'PostgreSQL console (psql)'),
    ('python2', 'Python 2'),
    ('python3', 'Python 3'),
    ('restructuredtext', 'reStructuredText'),
    ('ruby', 'Ruby'),
    ('sass', 'Sass'),
    ('scala', 'Scala'),
    ('scss', 'SCSS'),
    ('sql', 'SQL'),
    ('xml', 'XML'),
    ('yaml', 'YAML'),
]
