
RUSSIAN_LETTERS = 'АБВГДЕЁЖЗИЙКЛМНОПРТУФХЦЧШЩЫЭЮЯабвгдеёжзийклмнопрстуфхцчшщыьэюя'

CHOICES_LEXERS = [
    ('awk', 'Awk'),
    # ('base_makefile', 'Base Makefile'),
    ('bash', 'Bash'),
    ('coffeescript', 'CoffeeScript'),
    ('css', 'CSS'),
    ('css_django_jinja', 'CSS+Django/Jinja'),
    ('django_jinja', 'Django/Jinja'),
    ('html', 'HTML'),
    ('html_django_jinja', 'HTML+Django/Jinja'),
    ('ipython3', 'IPython'),
    ('javascript', 'JavaScript'),
    ('javascript_django_jinja', 'JavaScript+Django/Jinja'),
    ('json', 'JSON'),
    # ('lesscss', 'LessCss'),
    # ('makefile', 'Makefile'),
    ('mysql', 'MySQL'),
    ('numpy', 'NumPy'),
    ('postgresql_console', 'PostgreSQL'),
    # ('python2', 'Python 2'),
    ('python3', 'Python'),
    ('restructuredtext', 'reStructuredText'),
    # ('sass', 'Sass'),
    ('sql', 'SQL'),
    ('xml', 'XML'),
    ('yaml', 'YAML'),
]


PRETTY_COLORS = [
    '#222222',
    '#85cd85',
    '#85cd1c',
    '#008000',
    '#808080',
    '#0000FF',
    '#808000',
    '#008080',
    '#800000',
    '#800080',
    '#EEAA00',
    '#EE4921',
    '#8B5A8B',
    '#003FCD',
    '#c9366e',
    '#b1744e',
    '#f292c7',
    '#9e617b',
]
