
import factory

from .models import *


class Factory_Tag(factory.DjangoModelFactory):

    class Meta:
        model = Tag

    name = factory.Faker('slug', locale='ru')


Tag.objects.filter().delete()

Factory_Tag(name='python-pickle')
Factory_Tag(name='python-shutil')
Factory_Tag(name='python-os')
Factory_Tag(name='python-collections')
Factory_Tag(name='python-itertools')
Factory_Tag(name='sqlite')
Factory_Tag(name='mysql')
Factory_Tag(name='postgresql')
Factory_Tag(name='django-urls')
Factory_Tag(name='django-templates')
Factory_Tag(name='django-models')
Factory_Tag(name='django-views')
Factory_Tag(name='django-admin')
Factory_Tag(name='ubuntu')
Factory_Tag(name='debian')
Factory_Tag(name='linux mint')
Factory_Tag(name='sublime text')
Factory_Tag(name='emmet')
Factory_Tag(name='foundation')
Factory_Tag(name='bootstrap')
Factory_Tag(name='backbone.js')
Factory_Tag(name='angular.js')
Factory_Tag(name='jquery.js')
Factory_Tag(name='javascript')
Factory_Tag(name='django')
Factory_Tag(name='django-static')
Factory_Tag(name='django-media')
Factory_Tag(name='django-deploy')
Factory_Tag(name='django-app')
Factory_Tag(name='django-json')
Factory_Tag(name='pygments')
Factory_Tag(name='python-datetime')
Factory_Tag(name='python-xml')
Factory_Tag(name='json')
Factory_Tag(name='html')
Factory_Tag(name='html5')
Factory_Tag(name='css')
Factory_Tag(name='css3')
Factory_Tag(name='coffiscript')
Factory_Tag(name='ajax')
Factory_Tag(name='jquery-ajax')
Factory_Tag(name='django-ajax')
Factory_Tag(name='python-loggin')
Factory_Tag(name='python-glob')
Factory_Tag(name='python-math')
Factory_Tag(name='python-pathlib')
Factory_Tag(name='python-regex')
Factory_Tag(name='python-calendar')
Factory_Tag(name='javascript-regex')
Factory_Tag(name='javascript-math')
Factory_Tag(name='anaconda')
Factory_Tag(name='flake')
Factory_Tag(name='pep')
Factory_Tag(name='pypi')
Factory_Tag(name='nodejs')
Factory_Tag(name='grunt')
Factory_Tag(name='nmp')
Factory_Tag(name='pythonanywhere')
Factory_Tag(name='heroku')
Factory_Tag(name='openshift')
Factory_Tag(name='redhat')
Factory_Tag(name='digitalocean')
Factory_Tag(name='django-slug')
Factory_Tag(name='django-db-fields')
Factory_Tag(name='django-forms')
Factory_Tag(name='django-signals')
Factory_Tag(name='django-fixtures')
Factory_Tag(name='factory-boy')
Factory_Tag(name='nose')
Factory_Tag(name='pytest')
Factory_Tag(name='selenium')
Factory_Tag(name='django-testing')
Factory_Tag(name='python-testing')
Factory_Tag(name='javascript-testing')
Factory_Tag(name='jquery-plugins')
Factory_Tag(name='django-auth')
Factory_Tag(name='django-oath2')
Factory_Tag(name='python-urllib')
Factory_Tag(name='python-beutifulsoup')
Factory_Tag(name='html-video')
Factory_Tag(name='html-audio')
Factory_Tag(name='bootstrap-templates')
Factory_Tag(name='whitenoise')
Factory_Tag(name='python-pytz')
Factory_Tag(name='django-psycopg')
Factory_Tag(name='python-pil')
Factory_Tag(name='ipython')
Factory_Tag(name='bpython')
Factory_Tag(name='django-suit')
Factory_Tag(name='django-grappely')
Factory_Tag(name='django-captcha')
Factory_Tag(name='captcha')
Factory_Tag(name='python-debug')
Factory_Tag(name='django-debug')
Factory_Tag(name='django-coverage')
Factory_Tag(name='django-crispy-forms')
Factory_Tag(name='django-extensions')
Factory_Tag(name='django-model-utils')
Factory_Tag(name='git')
Factory_Tag(name='github')
Factory_Tag(name='linux')
Factory_Tag(name='gunicorn')
Factory_Tag(name='apache')
Factory_Tag(name='wsgi')
Factory_Tag(name='nginx')
Factory_Tag(name='font-awesome')
Factory_Tag(name='fansybox')
Factory_Tag(name='less')
Factory_Tag(name='sass')
Factory_Tag(name='Makefile')
Factory_Tag(name='Markdown')
Factory_Tag(name='reStucturedText')
Factory_Tag(name='django-sphinx')
Factory_Tag(name='jinja')
Factory_Tag(name='rest')
Factory_Tag(name='django-rest_framework')
